---
- hosts: all
  become: yes
  tasks:

  - name: copy timezone
    ansible.builtin.copy:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root

  - name: restart chronyd
    ansible.builtin.systemd:
      name: chronyd
      state: restarted
      enabled: yes

  - name: update the rpm
    ansible.builtin.dnf:
      name:
        - rpm
      state: latest
      update_only: yes

  - name: install packages
    ansible.builtin.yum: name={{ item }} state=latest
    with_items:
      - traceroute
      - tcpdump
      - net-tools
      - nmap
      - nano
      - mc

- hosts: centralServer
  become: true
  tasks:

  - name: install nginx
    ansible.builtin.yum: name={{ item }} state=latest
    with_items:
      - nginx

  - name: restarted nginx
    ansible.builtin.systemd:
      name: nginx
      state: restarted
      enabled: yes

  - name: del default gateway
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no

  - name: add route to 0.0.0.0/0
    ansible.builtin.shell:
      cmd: touch /etc/sysconfig/network-scripts/route-eth1 && echo "0.0.0.0/0 via 192.168.0.1" > /etc/sysconfig/network-scripts/route-eth1

#  - name: add default gateway
#    ansible.builtin.shell:
#      cmd: echo 'GATEWAY=192.168.0.1' >> /etc/sysconfig/network-scripts/ifcfg-eth1 && echo 'DEFROUTE=yes' >> /etc/sysconfig/network-scripts/ifcfg-eth1

  - name: restarted NetworkManager service
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
      enabled: yes

- hosts: Routers
  become: true
  tasks:

  - name: set up forward packages across routers
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

- hosts: centralRouter
  become: true
  tasks:

  - name: del default gateway
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no

  - name: add route to 0.0.0.0/0
    ansible.builtin.shell:
      cmd: touch /etc/sysconfig/network-scripts/route-eth1 && echo "0.0.0.0/0 via 192.168.255.1" > /etc/sysconfig/network-scripts/route-eth1

  - name: restarted NetworkManager service
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
      enabled: yes

  - name: set up iptables
    ansible.builtin.copy:
      src: ./files/knock.sh
      dest: /root/knock.sh
      owner: root
      group: root
      mode: 0770

# - hosts: inetRouter-1, inetRouter-2
#   become: true
#   tasks:

#   - name: install packages
#     ansible.builtin.yum:
#       name: "{{ packages }}"
#       state: present
#     vars:
#       packages:
#       - iptables
#       - iptables-services

#  - name: set up iptables
#    ansible.builtin.copy:
#      src: ./files/ipt-ri.txt
#      dest: /etc/sysconfig/iptables
#      owner: root
#      group: root
#      mode: 0600

#  - name: restart iptables
#    ansible.builtin.systemd:
#      name: iptables
#      state: restarted
#      enabled: true

- hosts: inetRouter-1
  become: true
  tasks:

  - name: install packages
    ansible.builtin.yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - iptables
      - iptables-services

  - name: add default gateway
    ansible.builtin.lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=yes

  - name: add route to 192.168.0.0/22
    ansible.builtin.shell:
      cmd: touch /etc/sysconfig/network-scripts/route-eth1 && echo "192.168.0.0/22 via 192.168.255.2" > /etc/sysconfig/network-scripts/route-eth1

  - name: set up iptables
    ansible.builtin.copy:
      src: ./files/ipt-ri.txt
      dest: /etc/sysconfig/iptables
      owner: root
      group: root
      mode: 0600

  - name: restarted iptables
    ansible.builtin.systemd:
      name: iptables
      state: restarted
      enabled: yes

  - name: restarted Network service
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
      enabled: yes

  - name: set up sshd
    ansible.builtin.copy:
      src: ./files/sshd-ri
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600

  - name: restarted sshd service
    ansible.builtin.systemd:
      name: sshd
      state: restarted
      enabled: yes

- hosts: all
  become: yes
  tasks:

  - name: Reboot the servers
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
